from django.urls import path
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetCompleteView
)
from django.utils.module_loading import import_string
from .views import (
     custom_logout_view, is_authenticated, signup,
     CustomPasswordResetView, CustomPasswordResetConfirmView,
     verify_email, send_verification_email_view, verification_email_sent,
     device_list, sign_out_session, sign_out_all_other_sessions,
     mfa_setup_view, mfa_verify_view, mfa_resend_view,
     mfa_disable_view, mfa_backup_codes_view,
)
from .settings import auth_settings
urlpatterns = [
    path('login/', import_string(auth_settings.LOGIN_VIEW), name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('signup/', signup, name='signup'),
    path('is-authenticated/', is_authenticated, name='is_authenticated'),
    path('password-reset/',
         CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-done/',
         PasswordResetDoneView.as_view(template_name='customauth/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='customauth/password_reset_complete.html'),
         name='password_reset_complete'),
    path('verify-email/<uidb64>/<token>/',
         verify_email,
         name='verify_email'),
    path('send-verification-email/',
         send_verification_email_view,
         name='send_verification_email'),
    path('verification-email-sent/',
         verification_email_sent,
         name='verification_email_sent'),
    path('devices/',
         device_list,
         name='device_list'),
    path('devices/sign-out/<uuid:session_id>/',
         sign_out_session,
         name='sign_out_session'),
    path('devices/sign-out-all/',
         sign_out_all_other_sessions,
         name='sign_out_all_other_sessions'),
    path('mfa/setup/', mfa_setup_view, name='mfa_setup'),
    path('mfa/verify/', mfa_verify_view, name='mfa_verify'),
    path('mfa/resend/', mfa_resend_view, name='mfa_resend'),
    path('mfa/disable/', mfa_disable_view, name='mfa_disable'),
    path('mfa/backup-codes/', mfa_backup_codes_view, name='mfa_backup_codes'),
]
