# Generated by Django 5.1.4 on 2024-12-31 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_customuser_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
