# Generated by Django 5.1.4 on 2024-12-31 15:27

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("customauth", "customuser")
    for row in MyModel.objects.all():
        row.uuid_id = uuid.uuid4()
        row.save(update_fields=["uuid_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_customuser_uuid_id_alter_customuser_metadata'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
