# Generated by Django 5.1.4 on 2024-12-31 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_auto_20241231_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
