# Generated by Django 5.1.4 on 2024-12-31 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_auto_20241231_1527'),
    ]

    operations = [
        # 1) Remove the old 'id' field
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),

        # 2) Rename 'uuid_id' to 'id'
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid_id',
            new_name='id',
        ),

        # 3) Make the new 'id' field primary
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(
                primary_key=True,
                default=uuid.uuid4,
                editable=False
            ),
        ),
    ]
