# Generated by Django 5.1.2 on 2024-11-13 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['status'], name='chatbot_app_status_702c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['created_at'], name='chatbot_app_created_10bcc1_idx'),
        ),
    ]
